const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FALSE: 'SIGNIN_FALSE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
}

export default userTypes;