const userTypes = {
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',

    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGNIN_FALSE: 'SIGNIN_FALSE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
}

export default userTypes;